### ISSUE TITLE
Using pybiocfilecache

### ISSUE THREAD

**Issue by jwokaty** [databio/geniml#3]
We discussed using interoperable caching for R/Python users on 4/10. @LiNk-NY checked that https://github.com/BiocPy/pyBiocFileCache doesn't use the same path for Python and R; however, we could agree to use the same path for `bbclient` and https://github.com/jwokaty/bedbaser. The default path appears to be `~/cache`, which I could use for `bedbaser` to make it agnostic.

**Comment by jkanche** [comment]
Hi all, Ran into this looking for something else. I think one solution might be is to agree on a common directory and set the location using app dirs ?

**Comment by khoroshevskyi** [comment]
We added pyBiocFileCache to bbclient. So now both Python and R can use cached data from same folder.
In Python and R you can specify where you store your cached files. Find more info here:
https://docs.bedbase.org/geniml/tutorials/pyBiocFileCache/ .

I think this issue is solved, close it if you think so

**Comment by khoroshevskyi** [comment]
From my side it seems like this issue is solved, reopen if needed. thx
